name: Build compose-unpacker docker image to Portainer
run-name: compose-unpacker ${{ github.event.inputs.unpacker_version }} release

on:
  workflow_dispatch:
    inputs:
      unpacker_version:
        description: "compose-unpacker version. e.g. 2.20.0"
        required: true
      release_branch:
        description: "release branch. e.g. release/2.20"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.event.inputs.release_branch }}
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
        with:
          driver-opts: image=moby/buildkit:v0.10.6
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build the image to portainer release
        run: |
          # make the script executeable 
          chmod +x "${GITHUB_WORKSPACE}/build/build_and_push.sh"
          # run the script
          "${GITHUB_WORKSPACE}/build/build_and_push.sh" portainer {{ github.event.inputs.unpacker_version }}
